// Prüft die Zuordnung Frage -> Prozess in index.html (Funktion route).
// Aufruf: node pruefung/routing.mjs   (Exit-Code 1 bei Abweichung)
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const src = html.slice(html.indexOf('function route(q)'), html.indexOf('function goAsk'));
const route = new Function(src + '\nreturn route;')();

// [Frage, erwarteter Prozess oder null = Fallback "noch keine Antwort"]
const FAELLE = [
  // Die Beispielfragen (DE) (Chips) müssen exakt treffen
  ['Ich ziehe von Bern nach Winterthur: Wie und bis wann melde ich mich ab und an?', 'move'],
  ['Ich wohne in Bern und brauche einen neuen Pass und eine Identitätskarte. Wie und wo bestelle ich die?', 'passport'],
  ['Ich wohne in Bern und schaffe meine Steuererklärung nicht bis Mitte März. Wie verlängere ich die Frist und was kostet das?', 'tax'],
  ['Ich bin Jahrgang 1962 und wohne in Thun: Wann und wo melde ich meine AHV-Rente an?', 'ahv'],
  ['Ich wohne in Thun und verliere Ende Monat meine Stelle. Wo und wann muss ich mich melden, und wie bekomme ich Arbeitslosengeld?', 'alv'],
  ['Bis wann kann ich meine Krankenkasse wechseln und wie geht das?', 'kk'],
  ['Ich wohne in Bern und mache mich mit einer Einzelfirma selbstständig. Was muss ich wo anmelden?', 'biz'],
  ['Ich wohne seit einigen Monaten in Bern und habe einen deutschen Führerausweis. Muss ich ihn umtauschen, und wie?', 'drv'],
  ['Wir sind beide Schweizer, wohnen in Zürich und wollen heiraten. Wie läuft das und was kostet es?', 'wed'],
  ['Ich wohne in der Stadt Bern und habe einen Hund übernommen. Wo melde ich ihn an und was kostet das?', 'dog'],
  ['Ich bin in Bern angestellt und habe ein Baby bekommen. Wie bekomme ich Kinderzulagen und wie viel gibt es?', 'fam'],
  ['Ich wohne in Bern und brauche für eine neue Wohnung einen Betreibungsregisterauszug. Wo bestelle ich ihn und was kostet er?', 'debt'],
  ['Ich brauche für eine neue Stelle einen Strafregisterauszug. Wie bestelle ich ihn und wie lange dauert es?', 'crim'],
  ['Ich wohne in Bern und habe ein Occasionsauto gekauft. Wie löse ich es ein und was kostet das?', 'car'],
  ['Ich lebe seit 12 Jahren in der Schweiz, davon 3 in der Stadt Bern, und habe den C-Ausweis. Kann ich mich einbürgern lassen und was kostet das?', 'nat'],
  ['Ich wohne im Kanton Bern und verdiene wenig. Bekomme ich Prämienverbilligung und muss ich sie beantragen?', 'pv'],
  ['Ich bin 22, wohne in Bern und wurde für den Militärdienst untauglich erklärt. Muss ich Wehrpflichtersatz zahlen und wie viel?', 'wpe'],
  ['Ich wohne in der Stadt Bern und will im Garten ein kleines Gartenhaus aufstellen. Brauche ich eine Baubewilligung?', 'bau'],
  ['Ich wohne in Bern und habe meine Identitätskarte verloren. Was muss ich tun und was kostet das?', 'lost'],
  ['Wir wohnen in der Stadt Bern und wollen unser Kind in die Kita geben. Bekommen wir Betreuungsgutscheine und wie beantragen wir sie?', 'kita'],
  ['Ich wohne in der Stadt Bern und komme mit meinem Geld nicht mehr durch. Wie beantrage ich Sozialhilfe?', 'soz'],
  ['Ich bin pensioniert, wohne in Thun und meine AHV-Rente reicht nicht. Kann ich Ergänzungsleistungen beantragen?', 'el'],
  ['Ich wohne in Bern und bin seit Monaten krank und arbeitsunfähig. Wie melde ich mich bei der IV an?', 'iv'],
  ['Ich bin angestellt und bekomme im Frühling ein Kind. Wie viel Mutterschaftsentschädigung erhalte ich und wie beantrage ich sie?', 'mse'],
  ['Ich bin angestellt und werde im Frühling Vater. Wie lange ist der Vaterschaftsurlaub und wie bekomme ich die Entschädigung?', 'pat'],
  ['Ich bin 17, wohne in Bern und will Auto fahren lernen. Wie bekomme ich den Lernfahrausweis?', 'lfa'],
  ['Ich wohne in der Stadt Bern und brauche eine Wohnsitzbestätigung. Wo bekomme ich sie und was kostet sie?', 'wsb'],
  ['Meine Mutter ist zu Hause in der Stadt Bern gestorben. Was muss ich jetzt tun und wo melde ich den Todesfall?', 'tod'],
  ['Ich wohne in der Stadt Bern und habe ein Auto. Wie bekomme ich eine Anwohnerparkkarte und was kostet sie?', 'pk'],
  ['Ich wohne in der Stadt Bern und will ein altes Sofa loswerden. Wie entsorge ich Sperrgut und was kostet das?', 'spg'],
  ['Ich habe in der Stadt Bern mein Portemonnaie verloren. Wie melde ich das beim Fundbüro?', 'fund'],
  ['Ein Kunde in Bern zahlt meine Rechnung über CHF 2\'000 nicht. Wie leite ich eine Betreibung ein?', 'bet'],
  ['Ich wohne im Kanton Bern und verkaufe mein Auto. Wie melde ich es ab und was passiert mit den Nummernschildern?', 'abm'],
  ['Ich arbeite neu in der Stadt Bern und gehe am Wochenende nach Hause ins Wallis. Wie melde ich mich als Wochenaufenthalter an?', 'wa'],
  ['Ich wohne in Bern und will aus der Kirche austreten. Wie geht das und ab wann zahle ich keine Kirchensteuer mehr?', 'kir'],
  ['Mir wurde in Bern das Velo gestohlen. Wie melde ich den Diebstahl bei der Polizei?', 'dieb'],
  ['Ich wohne in Bern und will einen Vorsorgeauftrag machen. Wie muss er aussehen und wo hinterlege ich ihn?', 'vor'],
  ['Ich wohne in der Stadt Bern und mein B-Ausweis läuft bald ab. Wie verlängere ich ihn?', 'aus'],
  ['Ich bin geschieden, wohne in Bern und will wieder meinen ledigen Namen tragen. Wie geht das?', 'nam'],
  ['Ich wohne in Bern und kann meine Steuerrechnung nicht auf einmal bezahlen. Kann ich in Raten zahlen?', 'rat'],
  ['Unser Sohn wird im Mai vier und wir wohnen in der Stadt Bern. Wann kommt er in den Kindergarten und wie melden wir ihn an?', 'kg'],
  ['Wir sind nicht verheiratet, wohnen in Bern und erwarten ein Kind. Wie anerkenne ich das Kind und was kostet das?', 'ank'],
  ['Unser Baby kommt bald in Bern zur Welt. Wer meldet die Geburt und was müssen wir tun?', 'geb'],
  ['Ich wohne im Kanton Bern und will an der Aare fischen. Welches Patent brauche ich und was kostet es?', 'fis'],
  ['Ich brauche einen Grundbuchauszug für mein Haus im Kanton Bern. Wie bestelle ich ihn und was kostet er?', 'gba'],
  ['Ich wohne in Bern und brauche einen Personenstandsausweis. Wo bestelle ich ihn und was kostet er?', 'zst'],
  ['Ich habe einen Zahlungsbefehl erhalten, schulde aber nichts. Wie erhebe ich Rechtsvorschlag und bis wann?', 'rv'],
  ['Ich habe ein schnelles E-Bike gekauft und wohne im Kanton Bern. Brauche ich ein Nummernschild und was kostet das?', 'mof'],
  ['Ich wohne im Kanton Bern und will eine Pistole kaufen. Wie bekomme ich einen Waffenerwerbsschein und was kostet er?', 'waf'],
  ['Ich beginne im August ein Studium, meine Eltern wohnen im Kanton Bern. Wie beantrage ich ein Stipendium und bis wann?', 'sti'],
  ['Meine Miete beruht auf einem Referenzzinssatz von 1,5 %. Kann ich eine Senkung verlangen und wie?', 'miet'],
  ['Ich zahle Quellensteuer und wohne im Kanton Bern. Kann ich eine Steuererklärung machen, um Abzüge geltend zu machen?', 'qst'],
  ['Mein Vater ist in Bern gestorben und die Bank verlangt einen Erbenschein. Wo bekomme ich ihn und was kostet er?', 'erb'],
  ['Ich ziehe in der Stadt Bern um. Wie reserviere ich vor dem Haus einen Parkplatz für den Umzugswagen?', 'upk'],
  ['Ich war zwei Jahre im Ausland und habe keine AHV bezahlt. Kann ich die Lücke nachzahlen?', 'ahl'],
  ['Mein WK fällt in meine Prüfungszeit an der Uni. Kann ich ihn verschieben und bis wann muss ich das beantragen?', 'mdv'],
  ['Ich bin militärdiensttauglich, will aber Zivildienst leisten. Wie stelle ich das Gesuch?', 'zivi'],
  ['Ich habe im Kanton Bern eine Parkbusse bekommen, finde sie aber ungerecht. Was kann ich tun und bis wann muss ich zahlen?', 'obu'],
  ['Ich bin vor Monaten ausgezogen und der Vermieter gibt die Mietkaution nicht frei. Wie komme ich an mein Geld?', 'kau'],
  ['Ich habe gekündigt und mein Chef gibt mir kein Arbeitszeugnis. Habe ich ein Recht darauf?', 'zeug'],
  ['Ich bin seit zwei Wochen krank. Muss mein Arbeitgeber mir weiter den Lohn zahlen und wie lange?', 'krl'],
  ['Wie viele Wochen Ferien stehen mir zu, und darf mein Chef mir die Ferien auszahlen statt sie zu gewähren?', 'fer'],
  ['Ich mache jede Woche Überstunden. Muss mein Arbeitgeber sie bezahlen, und mit Zuschlag?', 'ueb'],
  ['Ich arbeite seit drei Jahren in derselben Firma. Welche Kündigungsfrist gilt, und darf man mir kündigen, wenn ich krank bin?', 'kue'],
  ['Ich will meine Mietwohnung kündigen. Welche Frist gilt, und brauche ich einen Nachmieter?', 'mkue'],
  ['In meiner Mietwohnung ist Schimmel und der Vermieter reagiert nicht. Was kann ich tun?', 'mae'],
  ['Meine Nachbarn machen fast jede Nacht nach 22 Uhr Lärm. Was kann ich tun?', 'lae'],
  ['Ich habe eine Nebenkostenabrechnung mit hoher Nachzahlung bekommen. Was kann ich tun?', 'nk'],
  ['J’ai reçu un décompte de charges avec un gros montant à payer en plus. Que puis-je faire ?', 'nk'],
  ['Ho ricevuto un conguaglio delle spese accessorie molto alto. Cosa posso fare?', 'nk'],
  ['I got a service charge statement with a big extra payment for my flat. What can I do?', 'nk'],
  ['Darf die Verwaltung Hauswart-Nebenkosten verrechnen, wenn sie nicht im Mietvertrag stehen?', 'nk'],
  ['Darf ich ein Zimmer meiner Mietwohnung untervermieten?', 'um'],
  ['Puis-je sous-louer une chambre de mon appartement ?', 'um'],
  ['Posso subaffittare una camera del mio appartamento in affitto?', 'um'],
  ['Can I sublet a room in my rented flat?', 'um'],
  ['Darf ich meine Wohnung im Sommer auf Airbnb anbieten?', 'um'],
  ['Mein Vermieter hat die Miete um 6 % erhöht. Kann ich mich wehren?', 'mze'],
  ['Mon bailleur augmente mon loyer de 6 %. Puis-je contester ?', 'mze'],
  ['Il mio locatore ha aumentato la pigione del 6 %. Posso contestare?', 'mze'],
  ['My landlord is raising my rent by 6 %. Can I challenge it?', 'mze'],
  ['Mietzinserhöhung wegen höherem Referenzzinssatz: ist das erlaubt?', 'mze'],
  ['Der Referenzzinssatz ist gesunken. Kann ich eine Mietzinssenkung verlangen?', 'miet'],
  ['Mein Vermieter hat mir die Wohnung gekündigt. Kann ich mich wehren?', 'mvk'],
  ['Mon bailleur a résilié mon bail. Puis-je contester ?', 'mvk'],
  ['Il locatore mi ha disdetto l’appartamento. Posso contestare?', 'mvk'],
  ['My landlord has terminated my lease. Can I fight it?', 'mvk'],
  ['Kann ich eine Erstreckung des Mietverhältnisses verlangen?', 'mvk'],
  ['Kündigung durch Vermieter anfechten', 'mvk'],
  ['Ich will meine Wohnung kündigen. Welche Frist gilt?', 'mkue'],
  ['Ich wohne in Bern und ziehe nächsten Sommer ins Ausland. Was muss ich erledigen?', 'ausw'],
  ['J’habite à Berne et je pars m’installer à l’étranger l’été prochain. Que dois-je faire ?', 'ausw'],
  ['Abito a Berna e la prossima estate mi trasferisco all’estero. Cosa devo fare?', 'ausw'],
  ['I live in Bern and am moving abroad next summer. What do I need to do?', 'ausw'],
  ['Ich wandere nach Kanada aus. Wo melde ich mich ab?', 'ausw'],
  ['Ich ziehe von Bern nach Thun. Wo melde ich mich ab?', 'move'],
  ['Meine Steuerveranlagung ist zu hoch. Wie erhebe ich Einsprache?', 'stein'],
  ['Ma décision de taxation est trop élevée. Comment faire une réclamation ?', 'stein'],
  ['La mia decisione di tassazione è troppo alta. Come presento reclamo?', 'stein'],
  ['My tax assessment is too high. How do I object?', 'stein'],
  ['Wie lange habe ich Zeit für eine Einsprache gegen die Veranlagungsverfügung?', 'stein'],
  ['Kann ich meine AHV-Rente mit 63 vorbeziehen und wie viel weniger bekomme ich?', 'ahvv'],
  ['Puis-je anticiper ma rente AVS à 63 ans et de combien est-elle réduite ?', 'ahvv'],
  ['Posso anticipare la rendita AVS a 63 anni e di quanto viene ridotta?', 'ahvv'],
  ['Can I draw my OASI pension early at 63, and how much less do I get?', 'ahvv'],
  ['Ich möchte mit 64 in Frühpension gehen. Wie geht das bei der AHV?', 'ahvv'],
  ['Ich wechsle die Stelle. Was passiert mit meinem Geld in der Pensionskasse?', 'fzk'],
  ['Je change d’emploi. Que devient mon argent de la caisse de pension ?', 'fzk'],
  ['Cambio lavoro. Cosa succede ai miei soldi della cassa pensione?', 'fzk'],
  ['I’m changing jobs. What happens to my pension fund money?', 'fzk'],
  ['Wo finde ich vergessene Guthaben aus der Pensionskasse?', 'fzk'],
  ['Wie viel darf ich in die Säule 3a einzahlen und wann kann ich das Geld beziehen?', 's3a'],
  ['Combien puis-je verser dans le pilier 3a et quand puis-je retirer l’argent ?', 's3a'],
  ['Quanto posso versare nel pilastro 3a e quando posso ritirare i soldi?', 's3a'],
  ['How much can I pay into pillar 3a and when can I withdraw the money?', 's3a'],
  ['Kann ich verpasste Einzahlungen in die dritte Säule nachholen?', 's3a'],
  ['Ich hatte am Wochenende einen Unfall beim Skifahren. Wem muss ich das melden und wer zahlt?', 'unf'],
  ['J’ai eu un accident de ski ce week-end. À qui dois-je l’annoncer et qui paie ?', 'unf'],
  ['Questo fine settimana ho avuto un infortunio sciando. A chi devo annunciarlo e chi paga?', 'unf'],
  ['I had a skiing accident at the weekend. Who do I report it to and who pays?', 'unf'],
  ['I accidentally lost my passport. What now?', 'lost'],
  ['Wir adoptieren ein zweijähriges Kind. Haben wir Anspruch auf bezahlten Urlaub?', 'adop'],
  ['Nous adoptons un enfant de deux ans. Avons-nous droit à un congé payé ?', 'adop'],
  ['Adottiamo un bambino di due anni. Abbiamo diritto a un congedo pagato?', 'adop'],
  ['We are adopting a two-year-old child. Are we entitled to paid leave?', 'adop'],
  ['Unser Kind ist schwer krank. Kann ich bezahlt zu Hause bleiben, um es zu betreuen?', 'bue'],
  ['Notre enfant est gravement malade. Puis-je arrêter de travailler pour m’en occuper et être indemnisé ?', 'bue'],
  ['Nostro figlio è gravemente malato. Posso smettere di lavorare per assisterlo e ricevere un’indennità?', 'bue'],
  ['Our child is seriously ill. Can I take paid leave to care for them?', 'bue'],
  ['Ich bin krank. Muss mein Arbeitgeber den Lohn weiter zahlen?', 'krl'],
  ['Meine Frau und ich wollen uns scheiden lassen. Wie läuft das ab?', 'sch'],
  ['Ma femme et moi voulons divorcer. Comment cela se passe-t-il ?', 'sch'],
  ['Mia moglie e io vogliamo divorziare. Come funziona?', 'sch'],
  ['My wife and I want to get divorced. How does it work?', 'sch'],
  ['Wie bekomme ich nach der Scheidung meinen Ledignamen zurück?', 'nam'],
  ['Ich gehe drei Wochen in den WK. Wie viel Erwerbsersatz bekomme ich?', 'eod'],
  ['Je fais trois semaines de cours de répétition. Combien d’allocation pour perte de gain vais-je recevoir ?', 'eod'],
  ['Faccio tre settimane di corso di ripetizione. Quanta indennità di perdita di guadagno ricevo?', 'eod'],
  ['I have three weeks of military refresher training. How much loss of earnings compensation do I get?', 'eod'],
  ['Bekomme ich im Zivildienst weiter Lohn?', 'eod'],
  ['Meine Mutter ist 82 und braucht jeden Tag Hilfe beim Anziehen und Essen. Bekommt sie Geld von der AHV?', 'he'],
  ['Ma mère a 82 ans et a besoin d’aide chaque jour pour s’habiller et manger. Reçoit-elle de l’argent de l’AVS ?', 'he'],
  ['Mia madre ha 82 anni e ogni giorno ha bisogno di aiuto per vestirsi e mangiare. Riceve soldi dall’AVS?', 'he'],
  ['My mother is 82 and needs help every day with dressing and eating. Can she get money from OASI?', 'he'],
  ['Wie viel Hilflosenentschädigung gibt es bei mittlerer Hilflosigkeit?', 'he'],
  // Abgrenzungen, die heute stimmen
  ['Nachtruhestörung melden', 'lae'],
  ['tapage nocturne', 'lae'],
  ['rumore dei vicini', 'lae'],
  ['noisy neighbours', 'lae'],
  ['Mängelrüge schreiben', 'mae'],
  ['moisissure dans mon appartement', 'mae'],
  ['muffa in casa', 'mae'],
  ['The heating is broken in my flat', 'mae'],
  ['Nachmieter suchen', 'mkue'],
  ['résilier mon bail', 'mkue'],
  ['disdire il contratto di locazione', 'mkue'],
  ['How do I end my lease early?', 'mkue'],
  ['Ich ziehe um und muss mich anmelden', 'move'],
  ['Kündigungsfrist in der Probezeit', 'kue'],
  ['délai de congé', 'kue'],
  ['periodo di prova', 'kue'],
  ['What is my notice period?', 'kue'],
  ['Überzeit Zuschlag', 'ueb'],
  ['heures supplémentaires', 'ueb'],
  ['ore straordinarie', 'ueb'],
  ['Is overtime paid?', 'ueb'],
  ['Ferienanspruch mit 19', 'fer'],
  ['droit aux vacances', 'fer'],
  ['vacanze non godute', 'fer'],
  ['How many vacation days do I get?', 'fer'],
  ['Wie lange dauert der Vaterschaftsurlaub?', 'pat'],
  ['Lohnfortzahlung bei Krankheit', 'krl'],
  ['certificat médical dès le premier jour', 'krl'],
  ['salario in caso di malattia', 'krl'],
  ['Do I get sick pay?', 'krl'],
  ['Ich will die Krankenkasse wechseln', 'kk'],
  ['Zwischenzeugnis verlangen', 'zeug'],
  ['certificat de travail', 'zeug'],
  ['certificato di lavoro', 'zeug'],
  ['Can I ask for a reference letter?', 'zeug'],
  ['Mietzinsdepot zurück', 'kau'],
  ['récupérer ma garantie de loyer', 'kau'],
  ['deposito di garanzia', 'kau'],
  ['How do I get my rent deposit back?', 'kau'],
  ['Ordnungsbusse bezahlen', 'obu'],
  ['contester une amende d’ordre', 'obu'],
  ['contestare una multa', 'obu'],
  ['How do I pay a speeding fine?', 'obu'],
  ['Mein Velo wurde gestohlen', 'dieb'],
  ['Zivildienst beantragen', 'zivi'],
  ['demander le service civil', 'zivi'],
  ['servizio civile', 'zivi'],
  ['How do I apply for civilian service?', 'zivi'],
  ['Dienstverschiebungsgesuch', 'mdv'],
  ['reporter mon école de recrues', 'mdv'],
  ['spostare la scuola reclute', 'mdv'],
  ['How do I postpone my military service?', 'mdv'],
  ['Wie viel Wehrpflichtersatz muss ich zahlen?', 'wpe'],
  ['AHV-Beitragslücke', 'ahl'],
  ['lacunes de cotisation AVS', 'ahl'],
  ['estratto del conto individuale', 'ahl'],
  ['Do I have contribution gaps?', 'ahl'],
  ['Wann bekomme ich AHV-Rente?', 'ahv'],
  ['Parkverbot für Umzug', 'upk'],
  ['interdiction de stationner pour un déménagement', 'upk'],
  ['divieto di sosta per trasloco', 'upk'],
  ['no parking sign for my move', 'upk'],
  ['Ich ziehe nach Bern um', 'move'],
  ['Anwohnerparkkarte beantragen', 'pk'],
  ['Erbschaft ausschlagen', 'erb'],
  ['répudier la succession', 'erb'],
  ['rinunciare all’eredità', 'erb'],
  ['How do I renounce an inheritance?', 'erb'],
  ['Mein Vater ist gestorben, was muss ich tun?', 'tod'],
  ['nachträgliche ordentliche Veranlagung', 'qst'],
  ['impôt à la source', 'qst'],
  ['imposta alla fonte', 'qst'],
  ['I pay source tax', 'qst'],
  ['Frist für die Steuererklärung verlängern', 'tax'],
  ['Mietzinssenkung verlangen', 'miet'],
  ['demander une baisse de loyer', 'miet'],
  ['riduzione della pigione', 'miet'],
  ['Can I ask for a rent reduction?', 'miet'],
  ['Stipendien beantragen', 'sti'],
  ['demander une bourse d’études', 'sti'],
  ['borsa di studio', 'sti'],
  ['How do I apply for a scholarship?', 'sti'],
  ['Waffenerwerbsschein beantragen', 'waf'],
  ['permis d’acquisition d’armes', 'waf'],
  ['permesso d’acquisto di armi', 'waf'],
  ['How can I buy a gun in Switzerland?', 'waf'],
  ['Mofa einlösen', 'mof'],
  ['Mofa-Vignette erneuern', 'mof'],
  ['immatriculer un cyclomoteur', 'mof'],
  ['targa per ciclomotore', 'mof'],
  ['Do I need a plate for my moped?', 'mof'],
  ['Mein E-Bike wurde gestohlen', 'dieb'],
  ['Ich will mein Auto einlösen', 'car'],
  ['Wie lange habe ich Zeit für den Rechtsvorschlag?', 'rv'],
  ['faire opposition au commandement de payer', 'rv'],
  ['Ho ricevuto un precetto esecutivo', 'rv'],
  ['I received a payment order', 'rv'],
  ['Wie leite ich eine Betreibung ein?', 'bet'],
  ['Mein Kunde zahlt seine Rechnung nicht', 'bet'],
  ['Heimatschein bestellen', 'zst'],
  ['Familienausweis bestellen', 'zst'],
  ['commander un acte d’origine', 'zst'],
  ['certificato di famiglia', 'zst'],
  ['Where do I get a civil status document?', 'zst'],
  ['Wir wollen heiraten', 'wed'],
  ['Wem gehört dieses Grundstück? Grundbuch', 'gba'],
  ['extrait du registre foncier', 'gba'],
  ['estratto del registro fondiario', 'gba'],
  ['How do I get a land register extract?', 'gba'],
  ['Ich brauche einen Betreibungsauszug', 'debt'],
  ['Tagespatent Fischen', 'fis'],
  ['permis de pêche', 'fis'],
  ['Geburtsurkunde bestellen', 'geb'],
  ['annoncer la naissance', 'geb'],
  ['Kindesanerkennung vor der Geburt', 'ank'],
  ['reconnaissance de paternité', 'ank'],
  ['acknowledge paternity', 'ank'],
  ['paternity leave Switzerland', 'pat'],
  ['Chindsgi Anmeldung', 'kg'],
  ['Kita-Platz für unser Baby', 'kita'],
  ['Zahlungserleichterung Steuern', 'rat'],
  ['Steuererklärung Frist verlängern', 'tax'],
  ['facilités de paiement impôts', 'rat'],
  ['Ledigname wieder annehmen', 'nam'],
  ['nom de célibataire', 'nam'],
  ['Verfallsanzeige erhalten', 'aus'],
  ['prolonger mon permis de séjour', 'aus'],
  ['Ich habe den C-Ausweis, kann ich mich einbürgern lassen?', 'nat'],
  ['Vorsorgeauftrag Kosten', 'vor'],
  ['mandat pour cause d’inaptitude', 'vor'],
  ['Handy gestohlen', 'dieb'],
  ['vélo volé', 'dieb'],
  ['Mein Pass wurde gestohlen', 'lost'],
  ['Kirchenaustritt Brief', 'kir'],
  ['quitter l’Église', 'kir'],
  ['Heimatausweis für Bern', 'wa'],
  ['séjour hebdomadaire Berne', 'wa'],
  ['Nummernschilder deponieren', 'abm'],
  ['Auto abmelden', 'abm'],
  ['Nummernschilder für mein neues Auto', 'car'],
  ['Ich habe einen Zahlungsbefehl erhalten', 'rv'],
  ['commandement de payer', 'bet'],
  ['Betreibungsauszug für die Wohnungssuche', 'debt'],
  ['Ich habe einen Schlüssel gefunden', 'fund'],
  ['bureau des objets trouvés', 'fund'],
  ['Ich habe meine ID verloren', 'lost'],
  ['Sperrgut nach dem Umzug abholen lassen', 'spg'],
  ['déchetterie horaires', 'spg'],
  ['Parkkarte nach Umzug', 'pk'],
  ['carte de stationnement résidents', 'pk'],
  ['Bestattung organisieren', 'tod'],
  ['annoncer un décès', 'tod'],
  ['Mein Mann ist gestorben. Bekomme ich eine AHV-Witwenrente?', 'ahv'],
  ['Wohnsitzbescheinigung bestellen', 'wsb'],
  ['attestation de domicile', 'wsb'],
  ['Neuen Wohnsitz anmelden', 'move'],
  ['Theorieprüfung buchen', 'lfa'],
  ['Nothelferkurs für den Lernfahrausweis', 'lfa'],
  ['permis d’élève conducteur', 'lfa'],
  ['Ausländischen Führerausweis umtauschen', 'drv'],
  ['Papiurlaub tageweise beziehen', 'pat'],
  ['congé paternité', 'pat'],
  ['Vaterschaftsurlaub als Selbstständiger', 'pat'],
  ['Taggeld bei Mutterschaft', 'mse'],
  ['Mutterschaftsentschädigung als Selbstständige', 'mse'],
  ['congé maternité indemnité', 'mse'],
  ['Hundesteuer bezahlen', 'dog'],
  ['Bekomme ich als Selbstständige Kinderzulagen?', 'fam'],
  ['Ausbildungszulage für meine Tochter', 'fam'],
  ['Betreibungsauszug nach Umzug bestellen', 'debt'],
  ['Leumundszeugnis für den Arbeitgeber', 'crim'],
  ['Nummernschilder für mein neues Auto', 'car'],
  ['Ich ziehe um, muss ich den Fahrzeugausweis ändern?', 'move'],
  ['Wie hoch ist die Motorfahrzeugsteuer?', 'car'],
  ['Schweizer Pass nach der Einbürgerung', 'nat'],
  ['How do I get Swiss citizenship?', 'nat'],
  ['Krankenkasse zu teuer, gibt es eine Verbilligung?', 'pv'],
  ['Krankenkasse wechseln wegen hoher Prämie', 'kk'],
  ['Ersatzabgabe zurückfordern nach Zivildienst', 'wpe'],
  ['Baugesuch über eBau einreichen', 'bau'],
  ['Mein Pass wurde gestohlen', 'lost'],
  ['My passport was stolen', 'lost'],
  ['Ich brauche einen neuen Pass', 'passport'],
  ['Kinderzulage für mein Kind in der Kita', 'fam'],
  ['Anmeldung beim Sozialdienst', 'soz'],
  ['EL zur IV beantragen', 'el'],
  ['Ich habe eine IV-Rente', 'iv'],
  ['Ich ziehe mit meinem Hund um', 'dog'],
  ['Ich ziehe um, muss ich die Krankenkasse informieren?', 'move'],
  ['Ich will eine Firma gründen', 'biz'],
  ['Brauche ich einen Eintrag im Handelsregister?', 'biz'],
  ['Ab wann muss ich Mehrwertsteuer abrechnen?', 'biz'],
  ['Welche AHV-Beiträge zahle ich als Selbstständiger?', 'biz'],
  ['Steuererklärung als Selbstständige: Frist verlängern', 'tax'],
  ['AHV-Rente anmelden, ich war selbstständig', 'ahv'],
  ['Selbstständig nach Kündigung, muss ich zum RAV?', 'alv'],
  ['Muss ich mein Gewerbe anmelden?', 'biz'],
  ['Nach der Heirat brauche ich einen neuen Pass', 'passport'],
  ['Wann muss ich die Ehevorbereitung machen?', 'wed'],
  ['Ich bin verheiratet und mache die Steuererklärung', 'tax'],
  ['We want to get married in Switzerland', 'wed'],
  ['Hochzeit im Standesamt planen', 'wed'],
  ['Wie tausche ich meinen Führerschein aus den USA um?', 'drv'],
  ['Führerausweis: neue Adresse nach Umzug melden', 'move'],
  ['Ich brauche einen Lernfahrausweis', 'lfa'],
  ['Muss ich mit meinem Führerausweis aus Brasilien eine Kontrollfahrt machen?', 'drv'],
  ['Échanger mon permis de conduire étranger', 'drv'],
  ['How do I exchange my foreign driving licence?', 'drv'],
  ['Je deviens indépendant, que faire ?', 'biz'],
  ['Registering as self-employed in Switzerland', 'biz'],
  ['Mir wurde gekündigt, was nun?', 'alv'],
  ['Wie melde ich mich beim RAV an?', 'alv'],
];

// Bekannte offene Fehler (Stand 7.10.2026). Werden angezeigt, brechen den Test aber nicht ab.
// Wer einen davon behebt, verschiebt ihn nach oben in FAELLE.
const OFFEN = [
  ['Pensionskasse auszahlen lassen', null],               // landet bei AHV (2. statt 1. Säule)
  ['Ich möchte meine Adresse bei der Steuerverwaltung ändern', 'move'], // landet bei Steuerfrist
  ['Ich verliere meine Stelle', 'alv'],                   // kein Treffer, Fallback
  ['Stellensuche nach Kündigung', 'alv'],                 // kein Treffer, Fallback
];

// Alle Beispielfragen (Chips) in DE/FR/IT/EN müssen ihren Prozess treffen
const KEYS = ['move', 'passport', 'tax', 'ahv', 'alv', 'kk', 'biz', 'drv', 'wed', 'dog', 'fam', 'debt', 'crim', 'car', 'nat', 'pv', 'wpe', 'bau', 'lost', 'kita', 'soz', 'el', 'iv', 'mse', 'pat', 'lfa', 'wsb', 'tod', 'pk', 'spg', 'fund', 'bet', 'abm', 'wa', 'kir', 'dieb', 'vor', 'aus', 'nam', 'rat', 'kg', 'ank', 'geb', 'fis', 'gba', 'zst', 'rv', 'mof', 'waf', 'sti', 'miet', 'qst', 'erb', 'upk', 'ahl', 'mdv', 'zivi', 'obu', 'kau', 'zeug', 'krl', 'fer', 'ueb', 'kue', 'mkue', 'mae', 'lae', 'nk', 'um', 'mze', 'mvk', 'ausw', 'stein', 'ahvv', 'fzk', 's3a', 'unf', 'adop', 'bue', 'sch', 'eod', 'he'];
const chipRe = /\{"?l"?:\s*"([^"]+)",\s*"?q"?:\s*"([^"]+)"\}/g;
let m, n = 0;
while ((m = chipRe.exec(html))) FAELLE.push([m[2], KEYS[n++ % KEYS.length]]);
if (n !== 4 * KEYS.length) { console.log(`FEHLER: ${n} statt ${4 * KEYS.length} Beispielfragen gefunden`); process.exit(1); }

let fehler = 0;
for (const [frage, soll] of FAELLE) {
  const ist = route(frage);
  const ok = ist === soll;
  if (!ok) fehler++;
  console.log(`${ok ? 'OK    ' : 'FEHLER'} soll=${String(soll).padEnd(8)} ist=${String(ist).padEnd(8)} ${frage}`);
}
console.log(`\n${FAELLE.length - fehler}/${FAELLE.length} Pflichtfälle korrekt\n\nBekannte offene Fehler:`);
for (const [frage, soll] of OFFEN) {
  const ist = route(frage);
  console.log(`${ist === soll ? 'BEHOBEN' : 'OFFEN  '} soll=${String(soll).padEnd(8)} ist=${String(ist).padEnd(8)} ${frage}`);
}
process.exit(fehler ? 1 : 0);
